// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts", // Phase 2 — mock-data.ts 이식 (D-04)
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // DIRECT_URL uses port 5432 (direct, not pooler) — required by `prisma migrate dev`
    // per RESEARCH.md §Key Finding #6
    directUrl: process.env["DIRECT_URL"],
  },
});
