// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//
// Phase 4 cleanup (04-10): load .env.local explicitly (preferred over .env) because
// the repo's default .env file contains a Prisma-CLI boilerplate URL that corrupts
// the real Supabase DATABASE_URL. Also dropped the `directUrl` field because
// @prisma/config 7.x Datasource type only supports { url, shadowDatabaseUrl }.
// DIRECT_URL is still consumed via process.env by the runtime (src/lib/db/index.ts
// uses it for the direct pg adapter); Prisma CLI picks it up from the env too.
import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local", override: true });
loadEnv({ path: ".env" }); // fallback for any keys not present in .env.local
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts", // Phase 2 — mock-data.ts 이식 (D-04)
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
